### ISSUE TITLE
变量名缺少对关键词的检查

### ISSUE THREAD

**Issue by Sihuai2412** [LKBaka/FoxScript#10]
如题
```
>>> print(123)
123
>>> dim print = 6
>>> print(123)
Error: 不是一个函数: INTEGER_OBJ
```
（尽管这并不在正常语法内，但缺少必要的检查）

**Comment by zi2ven** [comment]
实际上这个可以是正常的类似python

**Comment by LKBaka** [comment]
> 如题
> 
> ```
> >>> print(123)
> 123
> >>> dim print = 6
> >>> print(123)
> Error: 不是一个函数: INTEGER_OBJ
> ```
> 
> （尽管这并不在正常语法内，但缺少必要的检查）

有没有可能啊，python也一样
