### ISSUE TITLE
一些bug和建议

### ISSUE THREAD

**Issue by HazeMa0** [LKBaka/FoxScript#3]
由于内容较多，我放弃了“一个issue应当专注于一个问题”的原则。请你阅读。
### 1. [Bug] while表达式的条件判断并不准确。
例如以下代码执行后，i应该是0，而不是-1：
```
>>> dim i = 4
>>> while i > 0
... i = i - 1
... endwhile
>>> i
-1
```
### 2. [建议] 对负数词法规则的设计并不友好。
现有的词法分析要求：只要“-”后面是数字就会认为“-”的语义是符号而不是减号。这可能会对用户造成困扰。
例如下面代码就是令人疑惑的，尽管这可以被理解为一种奇特的设计：
```
>>> 1+2
3
>>> 1-2
-2
>>> 1 - 2
-1
```
#### 3.1 return语句不应该出现在函数外面。
```
>>> return 1
1
```
#### 3.2 禁止不应该被允许的表达式。
```
>>> dim a = /
>>> a
```
（经过检查，a此时实际上是null。这很危险，可能引起解释器运行的异常。）

**Comment by HazeMa0** [comment]
### 4. [小bug] 语句块里的语句应当和语句块外的语句一视同仁。
下面的代码里，a在if语句块内，就不会输出任何值，在if语句块外却会输出值。
```
>>> if 1 then
... a
... endif
>>> a
1
```

### 5. [bug与建议] 更完整的面向对象支持。
#### 5.1 有些类不应该被实例化，比如Console。
#### 5.2 这些类被错误地实例化后，方法调用会出现问题。
```
>>> IO.Console.WriteLine(1)
1
>>> Dim a as IO.Console
>>> a.WriteLine(1)
（未经处理的异常:  System.NullReferenceException: 未将对象引用设置到对象的实例。）
```
#### 5.3 展望未来，可以考虑区分静态方法和实例方法、静态对象和实例对象。
#### 5.4 展望未来的未来，可以考虑添加继承特性。这可能会引入大量的bug。

**Comment by LKBaka** [comment]
说的道理。
源代码是这样的
```
'While循环
While TryCast(cond_obj, Fox_Bool).Value
    '再次计算条件表达式的值
    cond_obj = Eval(while_stmt.LoopCondition, env)

    '计算While语句欲循环的代码
    Dim r = Eval(while_stmt.LoopBlock, env)
    If r Is Nothing Then Continue While
    If IsError(r) Then Return r

    r.Inspect()
End While
```

也就是说起码条件求完后还得再执行一次后才会结束
现在我修复了这个问题

```
>>> dim i = 4
>>> while i > 0
...     i = i - 1
... endwhile
>>> i
0
>>>
```

**Comment by LKBaka** [comment]
其实
```
>>> 1-2
-2
```
也是因为语法分析不健全的原因

**Comment by LKBaka** [comment]
至于
```
Dim a as IO.Console
```
我可以告诉你 As 这个语法我还没有添加

**Comment by LKBaka** [comment]
```
>>> if 1 then
... a
... endif
>>> a
1
```
试试 if 1 then a endif ？
他会正常的返回1
不过你说的我会考虑的

**Comment by HazeMa0** [comment]
### 6.[Bug] 对 else 语句的执行并不准确
一般来说，现代编程语言都规定，在一次运行时if只能流入其中一个分支。不能在进入一个分支后仍然判断else。
然而下面的例子没有正常工作：
```
>>> if a == 1 then
... a = 2
... elseif a == 2 then
... a = 3
... endif
>>> a
3
```

**Comment by HazeMa0** [comment]
### 7. [bug/建议] 应当添加嵌套语句的支持
现代编程语言允许语句的嵌套。然而，FoxScript在错误的时机中断了if语句的输入：
```
>>> a = 4
>>> b = 3
>>> if a == 3 then
... a = 11111
... if b == 3 then
... a = 22222
... else
... a = 33333
... endif
Nothing
```

**Comment by LKBaka** [comment]
> ### 2. [建议] 对负数词法规则的设计并不友好。
> 现有的词法分析要求：只要“-”后面是数字就会认为“-”的语义是符号而不是减号。这可能会对用户造成困扰。 例如下面代码就是令人疑惑的，尽管这可以被理解为一种奇特的设计：
> 
> ```
> >>> 1+2
> 3
> >>> 1-2
> -2
> >>> 1 - 2
> -1
> ```
> 

感谢您的建议，我现在找到了原因
请看以下代码
```
'如果下一个字符是数字
If Char.IsDigit(PeekChar()) Then
    '读取字符 (没有这行代码会报错 因为当前字符还是 "-" ) 
    ReadChar()
    '读取数字
    Dim num = "-" & ReadIntNumber()
    tkn = New Token(TokenType.INTNUMBER, num, _line)
    Return tkn
End If
```

早期还没有写语法分析器时我认为语法分析器不会去判断这个数是否为负数，所以我写了这段代码，但现在我认为不需要了，现在语法分析器会将-1正常解析成-1，而1-2也会被解析成1 - 2。

```
>>> -1
-1
>>> 1-2
-1
```

**Comment by LKBaka** [comment]
> ### 6.[Bug] 对 else 语句的执行并不准确
> 一般来说，现代编程语言都规定，在一次运行时if只能流入其中一个分支。不能在进入一个分支后仍然判断else。 然而下面的例子没有正常工作：
> 
> ```
> >>> if a == 1 then
> ... a = 2
> ... elseif a == 2 then
> ... a = 3
> ... endif
> >>> a
> 3
> ```

我无法复现此问题，使用else也是如此，
```
>>> if a == 1 then
...     a = 2
... else
...     a = 3
... endif
>>> a
2
```

**Comment by LKBaka** [comment]
> ### 7. [bug/建议] 应当添加嵌套语句的支持
> 现代编程语言允许语句的嵌套。然而，FoxScript在错误的时机中断了if语句的输入：
> 
> ```
> >>> a = 4
> >>> b = 3
> >>> if a == 3 then
> ... a = 11111
> ... if b == 3 then
> ... a = 22222
> ... else
> ... a = 33333
> ... endif
> Nothing
> ```

老Bug了，我得花一点时间想想怎么修

**Comment by LKBaka** [comment]
> ### 7. [bug/建议] 应当添加嵌套语句的支持
> 现代编程语言允许语句的嵌套。然而，FoxScript在错误的时机中断了if语句的输入：
> 
> ```
> >>> a = 4
> >>> b = 3
> >>> if a == 3 then
> ... a = 11111
> ... if b == 3 then
> ... a = 22222
> ... else
> ... a = 33333
> ... endif
> Nothing
> ```

修复完了，现在不会这样了
```
>>> func outer(val)
...     func inner(val)
...             return val * 100
...     endfunc
...     return inner(val)
... endfunc

>>> outer(100)
10000
```

**Comment by zi2ven** [comment]
> ### 4. [小bug] 语句块里的语句应当和语句块外的语句一视同仁。
> 下面的代码里，a在if语句块内，就不会输出任何值，在if语句块外却会输出值。
> 
> ```
> >>> if 1 then
> ... a
> ... endif
> >>> a
> 1
> ```
就是说有没有一种可能if语句并不是一个标准的表达式呢？

**Comment by LKBaka** [comment]
> ### 4. [小bug] 语句块里的语句应当和语句块外的语句一视同仁。
> 下面的代码里，a在if语句块内，就不会输出任何值，在if语句块外却会输出值。
> 
> ```
> >>> if 1 then
> ... a
> ... endif
> >>> a
> 1
> ```

已修复
```
>>> if 1 then
...     1
... endif
1
```

**Comment by LKBaka** [comment]
我在想我要不要关闭这个Issue，因为

> 5. [bug与建议] 更完整的面向对象支持。
> 5.1 有些类不应该被实例化，比如Console。
> 5.2 这些类被错误地实例化后，方法调用会出现问题。
> 
> ```
> >>> IO.Console.WriteLine(1)
> 1
> >>> Dim a as IO.Console
> >>> a.WriteLine(1)
> ```
>（未经处理的异常:  System.NullReferenceException: 未将对象引用设置到对象的实例。）
> 5.3 展望未来，可以考虑区分静态方法和实例方法、静态对象和实例对象。
> 5.4 展望未来的未来，可以考虑添加继承特性。这可能会引入大量的bug。

提到了 `更完整的面向对象支持。` 而我实际上仍未完成这个部分。我在思考

**Comment by zi2ven** [comment]
issue应该被关闭，因为这个issue重点是问题，如果你需要请求提供新功能，应该再次单开一个issue并提出如何改进，而不是提出大量的在短期内不可实现的目标
